APP_NAME = "Us"

# ── Phase 0: Context questions ────────────────────────────────────────────────

CONTEXT_QUESTIONS = [
    {
        "id": "c1",
        "framework": "Love Languages",
        "type": "multiselect",
        "label": "When you feel most loved, what matters most to you?",
        "hint": "Choose up to 2.",
        "max_select": 2,
        "options": [
            "Hearing kind words and compliments",
            "Spending real, uninterrupted time together",
            "Thoughtful gestures or surprises",
            "When someone helps out without being asked",
            "Physical affection — hugs, touch, closeness",
        ],
    },
    {
        "id": "c2",
        "framework": "Love Languages",
        "type": "multiselect",
        "label": "What would make you feel more appreciated by your partner?",
        "hint": "Choose up to 2.",
        "max_select": 2,
        "options": [
            "Them telling me specifically what they value about me",
            "Them being fully present and listening",
            "Them doing something kind without me asking",
            "A meaningful gesture or surprise",
            "Warm physical affection",
        ],
    },
    {
        "id": "c3",
        "framework": "Gottman: Love Maps",
        "type": "slider",
        "label": "How well do you know your partner's world right now?",
        "hint": "Their current worries, dreams, what's on their mind.",
        "min": 1,
        "max": 5,
        "min_label": "Not very well",
        "max_label": "Very well",
    },
    {
        "id": "c4",
        "framework": "Gottman: Fondness",
        "type": "choice",
        "label": "When you think about your partner, which feels most true right now?",
        "hint": None,
        "options": [
            "I naturally notice things I admire and appreciate about them",
            "I tell them often what I respect or love about them",
            "I find myself focusing more on what bothers me than what's good",
            "I feel fond of them but rarely say it out loud",
        ],
    },
    {
        "id": "c5",
        "framework": "Gottman: Four Horsemen",
        "type": "multiselect",
        "label": "When you and your partner disagree, what typically happens?",
        "hint": "Pick all that apply.",
        "max_select": 4,
        "options": [
            "We listen and try to understand each other",
            "One or both of us gets defensive",
            "We criticise each other's character, not just the issue",
            "One of us shuts down or goes quiet",
            "We talk it through and feel closer after",
        ],
    },
    {
        "id": "c6",
        "framework": "Attachment",
        "type": "slider",
        "label": "When you feel disconnected from your partner, what's your instinct?",
        "hint": "There's no right answer — just notice your pattern.",
        "min": 1,
        "max": 5,
        "min_label": "Seek closeness",
        "max_label": "Need space",
    },
    {
        "id": "c7",
        "framework": "Attachment",
        "type": "choice",
        "label": "When your partner needs space or seems distant, how do you feel?",
        "hint": None,
        "options": [
            "I trust they care, even when they need time alone",
            "I worry they're upset with me or pulling away",
            "I'm relieved — I enjoy that breathing room too",
            "I feel hurt or shut out",
        ],
    },
    {
        "id": "c8",
        "framework": "Attachment",
        "type": "choice",
        "label": "I feel most secure in a relationship when...",
        "hint": None,
        "options": [
            "My partner shows me regularly that they're committed",
            "We have clear rhythms — time together and time apart",
            "We handle conflict by talking it through calmly",
            "I'm trusted to be myself without proving my loyalty",
        ],
    },
    {
        "id": "c9",
        "framework": "Needs: Safety",
        "type": "slider",
        "label": "How important is feeling safe and secure to you right now?",
        "hint": "Emotionally safe — seen, not judged.",
        "min": 1,
        "max": 5,
        "min_label": "Less important",
        "max_label": "Very important",
    },
    {
        "id": "c10",
        "framework": "Needs: Appreciation",
        "type": "slider",
        "label": "How important is feeling recognised and appreciated?",
        "hint": "That your efforts and who you are are noticed.",
        "min": 1,
        "max": 5,
        "min_label": "Less important",
        "max_label": "Very important",
    },
    {
        "id": "c11",
        "framework": "Needs: Autonomy",
        "type": "slider",
        "label": "How important is having the freedom to be yourself?",
        "hint": "Your own interests, space, and identity within the relationship.",
        "min": 1,
        "max": 5,
        "min_label": "Less important",
        "max_label": "Very important",
    },
    {
        "id": "c12",
        "framework": "RAS",
        "type": "slider",
        "label": "How satisfied are you with your relationship overall?",
        "hint": None,
        "min": 1,
        "max": 5,
        "min_label": "Not satisfied",
        "max_label": "Very satisfied",
    },
    {
        "id": "c13",
        "framework": "RAS",
        "type": "slider",
        "label": "How much has your relationship met your expectations?",
        "hint": None,
        "min": 1,
        "max": 5,
        "min_label": "Not at all",
        "max_label": "Completely",
    },
    {
        "id": "c14",
        "framework": "RAS",
        "type": "slider",
        "label": "How often are you glad you're together?",
        "hint": None,
        "min": 1,
        "max": 5,
        "min_label": "Rarely",
        "max_label": "Always",
    },
]

# ── Phase 1: Open-ended questionnaire ─────────────────────────────────────────

QUESTIONS = [
    {
        "id": "q1",
        "theme": "Connection",
        "label": "What does a really good day together look like for you?",
        "placeholder": "Maybe a slow morning, a walk, cooking together... describe it as you imagine it.",
        "hint": "Think about the texture of the day, not just the activities.",
    },
    {
        "id": "q2",
        "theme": "Appreciation",
        "label": "What small things make you feel genuinely appreciated?",
        "placeholder": "A specific compliment, remembering something you mentioned, a note...",
        "hint": "Think about moments when you've felt seen and valued.",
    },
    {
        "id": "q3",
        "theme": "Feeling Seen",
        "label": "When do you feel most understood by a partner?",
        "placeholder": "When they listen without trying to fix things, when they remember details...",
        "hint": "This is about emotional recognition, not just practical support.",
    },
    {
        "id": "q4",
        "theme": "Priority",
        "label": "How do you know when you are a priority to someone you love?",
        "placeholder": "They make time, they follow through, they choose you even when tired...",
        "hint": "What signals matter most to you?",
    },
    {
        "id": "q5",
        "theme": "Closeness",
        "label": "What role does physical closeness play for you?",
        "placeholder": "Hand-holding, hugs when stressed, sitting close on the sofa...",
        "hint": "How physical presence affects you — not just romance.",
    },
    {
        "id": "q6",
        "theme": "Communication",
        "label": "When something is bothering you, what do you need from your partner?",
        "placeholder": "Space to process first, someone to just listen, help solving it...",
        "hint": "Think about a recent moment when you needed support.",
    },
    {
        "id": "q7",
        "theme": "Growth",
        "label": "What does it look like when a relationship is helping both people grow?",
        "placeholder": "Encouraging each other's dreams, honest conversations, learning together...",
        "hint": "What would you look back on and feel proud of?",
    },
    {
        "id": "q8",
        "theme": "Conflict",
        "label": "What helps you feel safe and okay during or after a disagreement?",
        "placeholder": "A hug, hearing 'I'm not going anywhere', time to cool down first...",
        "hint": "What makes conflict feel survivable and even useful?",
    },
    {
        "id": "q9",
        "theme": "Wishes",
        "label": "What's one thing you wish your partner just knew about you?",
        "placeholder": "Take your time with this one.",
        "hint": "Something hard to say out loud. This is the most important answer — be honest.",
    },
    {
        "id": "q10",
        "theme": "Love",
        "label": 'Finish this sentence: "I feel most loved when..."',
        "placeholder": "...my partner notices I'm tired and just sits with me.",
        "hint": "Keep it simple and personal.",
    },
]

# ── Pillar definition placeholders ────────────────────────────────────────────

PILLAR_PLACEHOLDERS = [
    "Feeling heard",
    "Dedicated time together",
    "Physical warmth",
    "Growing side by side",
    "Knowing I'm a priority",
]

# ── Action item templates ──────────────────────────────────────────────────────
# Each set is matched to pillar keywords. Templates use {name} and {pillar}.

ACTION_TEMPLATE_SETS = {
    "heard": [
        "When {name} shares something hard, resist the urge to fix it — just listen and say 'that makes sense'.",
        "Ask {name} once a week: 'Is there anything you've been carrying that I haven't noticed?'",
        "When {name} talks about something that matters to them, follow up on it the next day.",
        "Before giving advice, ask: 'Do you want to vent, or do you want help figuring it out?'",
        "Notice when {name} goes quiet. Check in without making it a big deal.",
        "After a disagreement, tell {name} what you heard them say — even if you disagree with it.",
        "Put your phone down when {name} is talking. Full presence, not partial.",
    ],
    "time": [
        "Protect one evening a week that belongs only to you two — no phones, no errands.",
        "Ask {name}: 'What would a perfect evening together look like this week?' Then make it happen.",
        "When you're together, be actually together. Notice when you're physically present but mentally elsewhere.",
        "Plan something small and intentional — a walk, a meal, a film you both want to see.",
        "When {name} wants to spend time together and you're tired, try 20 minutes of full presence instead of declining.",
        "Tell {name} when you're looking forward to seeing them. It costs nothing and means a lot.",
        "Create a small ritual you both own — morning coffee, a nightly check-in, whatever fits your life.",
    ],
    "touch": [
        "Reach for {name}'s hand sometimes — not for any reason, just because.",
        "Notice what kind of physical contact {name} responds warmly to, and offer that more often.",
        "When {name} seems stressed, a hand on their shoulder or a hug says more than words.",
        "Don't wait for a 'reason' to be affectionate. Spontaneous warmth matters.",
        "Ask {name}: 'Are you getting enough closeness from me?' and mean it.",
        "Physical check-in: if it's been a while since you've been warm and close, close that gap.",
    ],
    "priority": [
        "Follow through on small things. Consistency builds trust more than grand gestures.",
        "When {name} needs you and you're busy, acknowledge it: 'I can't right now, but I'll be there by X.'",
        "Show up when it counts — even when it's inconvenient. {name} will remember that.",
        "Check in with {name} regularly: 'How are you doing — really?'",
        "When you say you'll do something, do it. Or renegotiate before it falls through.",
        "Put {name}'s things in your calendar. If it matters to them, treat it like it matters.",
        "Let {name} know you're thinking about them — a message, a small gesture during the day.",
    ],
    "growth": [
        "Ask {name} about their dreams — not just their to-do list. What do they actually want?",
        "Celebrate {name}'s wins, even the small ones. Say it out loud when you're proud of them.",
        "Be honest with {name} in a kind way. Growth needs truth, not just comfort.",
        "Encourage {name} to pursue something that's just for them — their own projects, goals, interests.",
        "Talk about the future together: where you're going, what you're building. Make it a shared story.",
        "When {name} is struggling with something, ask 'How can I support you?' rather than assuming.",
    ],
    "safety": [
        "When things are hard between you, say 'I'm not going anywhere' — and mean it.",
        "Don't leave a fight unresolved for more than a day. Even a small repair matters.",
        "After conflict, come back with warmth. The repair is more important than who was right.",
        "Tell {name} what you need when you're overwhelmed, so they're not left guessing.",
        "When {name} is upset, don't defend yourself first — acknowledge how they're feeling.",
        "Make it safe to say hard things. If {name} can't be honest with you, something is getting lost.",
    ],
    "appreciation": [
        "Notice something specific {name} did well today. Tell them — by name, not just 'thanks'.",
        "Write {name} a note — a real one — about what you love about them. Not for an occasion, just because.",
        "Tell {name} what you'd miss if they weren't here. Not as a joke. Actually mean it.",
        "When {name} does something that makes your life better, say so in the moment.",
        "Remember what {name} mentioned matters to them. Bring it back up. That's attention.",
        "Express gratitude for who {name} is, not just what they do.",
    ],
    "default": [
        "Ask {name} how you're doing with their pillar '{pillar}' — be open to the answer.",
        "Notice this week: are your actions reflecting that '{pillar}' matters to {name}?",
        "Check in: 'Is there something small I could do that would make a difference for you?'",
        "Talk about '{pillar}' together — ask {name} what it looks like when it's going well.",
        "Commit to one small action this week that honours {name}'s need for '{pillar}'.",
        "When in doubt, ask. '{name}, what does {pillar} look like for you today?'",
    ],
}

PILLAR_KEYWORD_MAP = {
    "heard": ["hear", "listen", "understand", "seen", "understood", "voice", "vent", "talk"],
    "time": ["time", "together", "day", "evening", "morning", "present", "moment", "slow", "quality"],
    "touch": ["touch", "physical", "close", "hug", "affection", "warm", "hold", "near", "body"],
    "priority": ["priority", "first", "important", "matter", "choose", "show up", "follow through", "consistent"],
    "growth": ["grow", "growth", "learn", "dream", "future", "encourage", "support", "develop", "goal"],
    "safety": ["safe", "secure", "trust", "conflict", "disagree", "fight", "repair", "honest"],
    "appreciation": ["appreciat", "recogni", "notice", "thank", "gratitude", "value", "proud", "seen"],
}
